facebook:
  clientID: "**INSERT**"
  clientSecret: "**INSERT**"
  callbackURL: "http://localhost:8080/v0/auth/facebook/callback"
google:
  clientID: "**INSERT**"
  clientSecret: "**INSERT**"
  callbackURL: "http://localhost:8080/v0/auth/google/callback"
twitter:
  consumerKey: "**INSERT**"
  consumerSecret: "**INSERT**"
  callbackURL: "http://localhost:8080/v0/auth/twitter/callback"
github:
  clientID: "**INSERT**"
  clientSecret: "**INSERT**"
  callbackURL: "http://localhost:8080/v0/auth/github/callback"
