useDb: true
useSSL: false
privateKey: ''
sslCert: ''
session:
  secret: '**INSERT SESSION SECRET**'
  cookie:
    maxAge: 2419200000
  resave: false
  saveUninitialized: true
db:
  connectionLimit: 100
  multipleStatements: true
  host: 'localhost'
  user: '**INSERT DB USER**'
  password: '**INSERT DB PASS**'
  database: '** INSERT DB NAME**'
  debug: false
