useDb: false
useSSL: false
privateKey: ''
sslCert: ''
serveStatic: false
session:
  secret: 'octoturtlebeans'
  cookie:
    maxAge: 2419200000
  resave: false
  saveUninitialized: true
db:
  connectionLimit: 100
  multipleStatements: true
  host: 'localhost'
  user: ''
  password: ''
  database: ''
  debug: false
